### PR TITLE
[FLOC-1927] Generate a dedicated builder for each platform and supported OS

### PR DESCRIPTION
**Pull request by myechuri**
Design for https://clusterhq.atlassian.net/browse/FLOC-1927

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/86)

### CODE REVIEW

**Comment by tomprince** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.
Reviewed files:
- flocker_bb/builders/flocker.py @ r1

---

<sup>**[flocker_bb/builders/flocker.py, line 675 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-JphWiriUkSvx2Bbr7sc)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/dc91f56c10333d3680f3c2c8468f05f92c830c01/flocker_bb/builders/flocker.py#L675)):</sup>
I think we still just want to run the specific tests, rather than the entire test-suite here.

---

<sup>**[flocker_bb/builders/flocker.py, line 678 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-JphXIgPj2n_4xqv7kbU)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/bcb697a837bf76c8160ee16f42e26edb3c05523b/flocker_bb/builders/flocker.py#L678)):</sup>
I think there might be enough different bits of configuration that it is worthwhile doing something like [this](https://github.com/ClusterHQ/build.clusterhq.com/blob/ebs_functional_test_builder-FLOC-1927/flocker_bb/builders/flocker_vagrant.py#L343-L358).

---

<sup>**[flocker_bb/builders/flocker.py, line 704 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-JphXc3rL649AWpqNTXR)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/bcb697a837bf76c8160ee16f42e26edb3c05523b/flocker_bb/builders/flocker.py#L704)):</sup>
And then you can do [this](https://github.com/ClusterHQ/build.clusterhq.com/blob/ebs_functional_test_builder-FLOC-1927/flocker_bb/builders/flocker_vagrant.py#L441-L444)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Comment by tomprince** [comment]
This looks good. There are a couple of minor comments to address. In addition, this should be tested on a staging server, and there are also the corresponding flocker changes to make (in a seperate subtask).

---

Review status: all files reviewed, 6 unresolved discussions, all commit checks successful.
Reviewed files:
- flocker_bb/builders/flocker.py @ r2

---

<sup>**[flocker_bb/builders/flocker.py, line 36 \[r2\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-Jpi1ilWwEgA0Vceg5LA)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/2bed94ee1814e1bf5c77a0b2d9b1efdc3aa1b932/flocker_bb/builders/flocker.py#L36)):</sup>
If we are always providing it, no reason for there to be a default value. (Especially since I think we'd blow up elsewhere if we used it.

---

<sup>**[flocker_bb/builders/flocker.py, line 48 \[r2\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-Jpi-uZBvZlMTRbRp-zM)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/2bed94ee1814e1bf5c77a0b2d9b1efdc3aa1b932/flocker_bb/builders/flocker.py#L48)):</sup>
I think we should keep the name like we have now, so
```python
['flocker','functional', self.provider, self.distribution, 'storage-driver']
```
or so.

---

<sup>**[flocker_bb/builders/flocker.py, line 61 \[r2\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-Jpi-dNcBHJw23b8i1US)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/2bed94ee1814e1bf5c77a0b2d9b1efdc3aa1b932/flocker_bb/builders/flocker.py#L61)):</sup>
I'm not entirely happy with having all this configuration hidden inside ``@property``s. But it is probably good enough for now.

---

<sup>**[flocker_bb/builders/flocker.py, line 79 \[r2\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-Jpi0S8H_lWlXYy8TT26)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/2bed94ee1814e1bf5c77a0b2d9b1efdc3aa1b932/flocker_bb/builders/flocker.py#L79)):</sup>
We should use `aws` to match what the acceptance tests do.

---

<sup>**[flocker_bb/builders/flocker.py, line 86 \[r2\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-Jpi1JTcWpo9Omxjj5bX)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/2bed94ee1814e1bf5c77a0b2d9b1efdc3aa1b932/flocker_bb/builders/flocker.py#L86)):</sup>
Looking at buildbot's code, it appears that locks are compared by name, so we should use a different name for this one, compared to the acceptance test one (probably by putting `functional` vs. `acceptance` into the name.

Also, the count probably wants to be `1` here.

---

<sup>**[flocker_bb/builders/flocker.py, line 744 \[r2\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-Jpi2-visiPADV44x7We)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/2bed94ee1814e1bf5c77a0b2d9b1efdc3aa1b932/flocker_bb/builders/flocker.py#L744)):</sup>
Since this doesn't vary, I think it should be specified explictly here, rather than indirected.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Comment by myechuri** [comment]
Review status: all files reviewed, 6 unresolved discussions, all commit checks successful.

---

<sup>**[flocker_bb/builders/flocker.py, line 48 \[r2\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-Jpi-uZBvZlMTRbRp-zM)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/2bed94ee1814e1bf5c77a0b2d9b1efdc3aa1b932/flocker_bb/builders/flocker.py#L48)):</sup>
Fixed, thanks!

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Comment by myechuri** [comment]
Review status: all files reviewed, 6 unresolved discussions, all commit checks successful.

---

<sup>**[flocker_bb/builders/flocker.py, line 79 \[r2\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-Jpi0S8H_lWlXYy8TT26)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/2bed94ee1814e1bf5c77a0b2d9b1efdc3aa1b932/flocker_bb/builders/flocker.py#L79)):</sup>
Fixed. Thanks!

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Comment by myechuri** [comment]
Review status: all files reviewed, 6 unresolved discussions, all commit checks successful.

---

<sup>**[flocker_bb/builders/flocker.py, line 86 \[r2\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-Jpi1JTcWpo9Omxjj5bX)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/2bed94ee1814e1bf5c77a0b2d9b1efdc3aa1b932/flocker_bb/builders/flocker.py#L86)):</sup>
Fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Comment by myechuri** [comment]
Review status: all files reviewed, 6 unresolved discussions, all commit checks successful.

---

<sup>**[flocker_bb/builders/flocker.py, line 744 \[r2\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-Jpi2-visiPADV44x7We)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/2bed94ee1814e1bf5c77a0b2d9b1efdc3aa1b932/flocker_bb/builders/flocker.py#L744)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Comment by myechuri** [comment]
Thanks, Tom , for the quick feedback! 

i have been looking at flocker changes for past one hour: trying to understand how run-acceptance-tests gathers Trial args and processes them, and attempting to emulate that. Please correct me if that is not the right direction.

For testing, can you please point me to setting up a staging server? Thanks a lot!!!

---

Review status: 0 of 1 files reviewed, 6 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Comment by tomprince** [comment]
You don't need anything like that. You just need to arrange that the tests get skipped if the environment variable defined here isn't defined.

---

Review status: 0 of 1 files reviewed, 6 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Comment by tomprince** [comment]
https://github.com/ClusterHQ/build.clusterhq.com#test-changes-on-staging-server has some words on setting up a staging server.

---

Review status: 0 of 1 files reviewed, 6 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Comment by tomprince** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.
Reviewed files:
- flocker_bb/builders/flocker.py @ r3

---

<sup>**[flocker_bb/builders/flocker.py, line 61 \[r3\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-JpiBWu2tbwRgjhKbAkO)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/ff53c69b9fd935e155c80286be737bb99f1db3de/flocker_bb/builders/flocker.py#L61)):</sup>
We should explictly fail here if something unexpected occurs. I typically do something like raise `NotImplementedError` with a message indiciating what was provided. (And the same below).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Comment by myechuri** [comment]
Thanks! Relevant flocker pull request: https://github.com/ClusterHQ/flocker/pull/1429/files

---

Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Comment by myechuri** [comment]
Thanks for the staging server instructions!

---

Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Comment by myechuri** [comment]
Review status: all files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[flocker_bb/builders/flocker.py, line 36 \[r2\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-Jpi1ilWwEgA0Vceg5LA)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/2bed94ee1814e1bf5c77a0b2d9b1efdc3aa1b932/flocker_bb/builders/flocker.py#L36)):</sup>
Fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Comment by myechuri** [comment]
Review status: 0 of 1 files reviewed, 3 unresolved discussions, all commit checks successful.

---

<sup>**[flocker_bb/builders/flocker.py, line 61 \[r3\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86#-JpiBWu2tbwRgjhKbAkO)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/ff53c69b9fd935e155c80286be737bb99f1db3de/flocker_bb/builders/flocker.py#L61)):</sup>
Thanks for the suggestion! Fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Comment by tomprince** [comment]
This looks good. Merge once its been tested in staging, and it has been verified that this an the corresponding flocker branch work together.

---

Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- flocker_bb/builders/flocker.py @ r4

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Comment by tomprince** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- flocker_bb/builders/flocker.py @ r5

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/86)

**Pull request merged**
