### PR TITLE
Record branch with finished build information

### PR DESCRIPTION
**Pull request by jml**
https://clusterhq.atlassian.net/browse/FLOC-2598
I want to get overall information on how flaky our tests & build process are, so that I can measure the success of our attempts to fix them, and so that we can have some sort of objective measure of when to stop and pursue other priorities.

Probably the easiest way to do this is to measure the rate of failed master builds. 

The first graph at http://metrics.build.clusterhq.com/failures shows the overall rate of failed builds, but it includes builds for branches, many of which we wouldn't expect to pass. 

To be able to filter for just master builds, we need to include a `branch` label in the metrics. This branch does that.

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/114)

### CODE REVIEW

**Comment by tomprince** [comment]
It'd probably be useful to record this information for pending and running builds, but that can be a followup.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[flocker_bb/monitoring.py, line 120 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114#-JtEAQta4IcFieRJM2JM)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/acae2de807c08817bcecbfbb386a653eb10b5a2d/flocker_bb/monitoring.py#L120)):</sup>
You actually want to look at the sourcestamp (`getSourceStamps`), rather than the property.

---

<sup>**[flocker_bb/monitoring.py, line 123 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114#-JtEAXco2Rv4hFs-ZYuH)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/acae2de807c08817bcecbfbb386a653eb10b5a2d/flocker_bb/monitoring.py#L123)):</sup>
Prometheus creates a new time series, so I'm not entirely sure that recording the branch is a sensible thing. (http://prometheus.io/docs/practices/naming/#labels) In any case, I think the interesting distinction is whether the build is master, a release, or a branch. So I think we should record that (as `branch_type`?) either as well, or instead.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114)

**Comment by jml** [comment]
I thought about it, but couldn't think of a query / graph where I'd want that info.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[flocker_bb/monitoring.py, line 120 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114#-JtEAQta4IcFieRJM2JM)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/acae2de807c08817bcecbfbb386a653eb10b5a2d/flocker_bb/monitoring.py#L120)):</sup>
I had thought of doing that, but `getSourceStamps` returns a list, and I wasn't clear on how to combine multiple distinct branches. What would you suggest?

---

<sup>**[flocker_bb/monitoring.py, line 123 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114#-JtEAXco2Rv4hFs-ZYuH)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/acae2de807c08817bcecbfbb386a653eb10b5a2d/flocker_bb/monitoring.py#L123)):</sup>
Right. (It really is very similar to the monitoring tool I used at my last workplace). 

Agree master/release/branch is a good categorization. How would you suggest that we make the distinction? Encoding naming conventions here in the monitoring module?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114)

**Comment by tomprince** [comment]
I could see it might be interesting, if we are looking at prioritizing different builds based on the branches involved. Also, if it is straightforward to do, it seems worthwhile to track it, so if we do have a use, we have data already.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[flocker_bb/monitoring.py, line 120 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114#-JtEAQta4IcFieRJM2JM)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/acae2de807c08817bcecbfbb386a653eb10b5a2d/flocker_bb/monitoring.py#L120)):</sup>
https://github.com/ClusterHQ/build.clusterhq.com/blob/master/flocker_bb/zulip_status.py#L161-L168 is some other code that is doing something similar. I'm not sure how to handle multiple stamps, but in practice we won't run into that, since we only have a single codebase. There will only be multiple sourcestamps if the build is configured with multiple codebases.

---

<sup>**[flocker_bb/monitoring.py, line 123 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114#-JtEAXco2Rv4hFs-ZYuH)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/acae2de807c08817bcecbfbb386a653eb10b5a2d/flocker_bb/monitoring.py#L123)):</sup>
There are some functions that get that already (https://github.com/ClusterHQ/build.clusterhq.com/blob/master/flocker_bb/steps.py#L366-L371), which do amount to encoding the naming convention. (I guess there are also release-maintenance branches, which are probably a separate type)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114)

**Comment by jml** [comment]
Added `branch_type` label to running counts. Doing it properly for pending counts proved a little too complex for this change.

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[flocker_bb/monitoring.py, line 120 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114#-JtEAQta4IcFieRJM2JM)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/acae2de807c08817bcecbfbb386a653eb10b5a2d/flocker_bb/monitoring.py#L120)):</sup>
Updated. I've added a `getBranch` helper that does that.

---

<sup>**[flocker_bb/monitoring.py, line 123 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114#-JtEAXco2Rv4hFs-ZYuH)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/acae2de807c08817bcecbfbb386a653eb10b5a2d/flocker_bb/monitoring.py#L123)):</sup>
I've created a `getBranchType` function that encodes that logic.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114)

**Comment by jml** [comment]
Have just verified that it works on staging:

```
buildbot_running_builds{branch_type="development",builder="flocker-lint",slave_class="aws/fedora-20",slave_number="1"} 0.0
buildbot_running_builds{branch_type="master",builder="flocker-lint",slave_class="aws/fedora-20",slave_number="0"} 0.0
...
buildbot_finished_builds_total{branch_type="development",builder="flocker-lint",result="success",slave_class="aws/fedora-20",slave_number="1"} 1.0
buildbot_finished_builds_total{branch_type="master",builder="flocker-lint",result="success",slave_class="aws/fedora-20",slave_number="0"} 1.0
```

---

Review status: 0 of 13 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114)

**Comment by tomprince** [comment]
Merge once #116 has landed, and optionally switching to t.p.constants.

---

Reviewed 8 of 10 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[flocker_bb/steps.py, line 44 \[r3\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114#-JtJRVXC6MIVyhpiq5IN)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/e94874619dec6c2bb055513fd95d76dea570d7f0/flocker_bb/steps.py#L44)):</sup>
:question: Consider using `twisted.python.constants.NamedConstants` here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114)

**Comment by jml** [comment]
Thanks! I knew there must be a library for this, but couldn't place it.

---

Review status: 3 of 10 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114)

**Comment by tomprince** [comment]
Looks good. Merge with the suggested changes, after testing, and observing that the prometheus labels show up correctly.

---

Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[flocker_bb/monitoring.py, line 110 \[r4\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114#-JtKNsm4KxW_WZl7M8y_)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/5b856b061d2eaa73a900bcbf613693048319f9ec/flocker_bb/monitoring.py#L110)):</sup>
And here.

---

<sup>**[flocker_bb/monitoring.py, line 122 \[r4\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114#-JtKNeplb0KzRfPlfdnf)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/5b856b061d2eaa73a900bcbf613693048319f9ec/flocker_bb/monitoring.py#L122)):</sup>
You'll want to use the name of the constant here and below. (And maybe make the constants lowercase)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114)

**Comment by tomprince** [comment]
Reviewed 2 of 2 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/114)

**Pull request merged**
