### PR TITLE
Make linkcheck builder warn.

### PR DESCRIPTION
**Pull request by tomprince**
https://clusterhq.atlassian.net/browse/FLOC-1226

### CODE REVIEW

**Comment by itamarst** [comment]
This seems like it would just make linkchecks always in warning mode, and always ignored, and so we still wouldn't catch real broken links?

**Comment by tomprince** [comment]
https://github.com/ClusterHQ/flocker/pull/1059 adds a step to the release process to check it. It isn't ideal, but it is better than having an always red builder. At least two of the failures have upstream issues.

**Comment by itamarst** [comment]
Ah, makes sense. Where's the staging buildbot so I can see how this looks?

**Comment by tomprince** [comment]
http://build.staging.clusterhq.com/boxes-flocker

**Comment by tomprince** [comment]
And the github status should show as "warnings build-linkcheck" but a green checkmark.

**Comment by tomprince** [comment]
(https://github.com/ClusterHQ/build.clusterhq.com/blob/master/flocker_bb/github.py#L132)

**Pull request merged**
