### PR TITLE
[FLOC-2604] Setup tox and travis.

### PR DESCRIPTION
**Pull request by tomprince**
https://clusterhq.atlassian.net/browse/FLOC-2604

This also fixes the tests that were failing.

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/116)

### CODE REVIEW

**Comment by jml** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[Dockerfile, line 4 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/116#-JtH_SspULStsdCxlKKB)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/ed4a9ce9293e166ce1f972123d18c07b510a349e/Dockerfile#L4)):</sup>
Can you please add comments explaining why this commented out code is here? (Or better yet, delete them).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/116)

**Comment by tomprince** [comment]
<sup>**[Dockerfile, line 4 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/116#-JtH_SspULStsdCxlKKB)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/ed4a9ce9293e166ce1f972123d18c07b510a349e/Dockerfile#L4)):</sup>
Out-of-scope.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/116)

**Comment by jml** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[Dockerfile, line 4 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/116#-JtH_SspULStsdCxlKKB)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/ed4a9ce9293e166ce1f972123d18c07b510a349e/Dockerfile#L4)):</sup>
Fair enough, although I'm surprised you're pushing back on this simple clean-up given that you asked me to increase the scope of other work I'm doing. I'd be happy to talk about it in some other forum. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/116)

**Comment by tomprince** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[Dockerfile, line 4 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/116#-JtH_SspULStsdCxlKKB)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/ed4a9ce9293e166ce1f972123d18c07b510a349e/Dockerfile#L4)):</sup>
If you are referring to #114, is specifically called out that it could be done in a followup issue. The reason I pushed back is that the way to address your comment is probably to update the base-box, re-add the `update` statement and get rid of both of the repo manipulation lines. That seems like a large-enough change that it should be done separately.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/116)

**Comment by tomprince** [comment]
<sup>**[Dockerfile, line 4 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/116#-JtH_SspULStsdCxlKKB)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/ed4a9ce9293e166ce1f972123d18c07b510a349e/Dockerfile#L4)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/116)

**Comment by jml** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[Dockerfile, line 4 \[r1\]](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/116#-JtH_SspULStsdCxlKKB)** ([raw file](https://github.com/clusterhq/build.clusterhq.com/blob/ed4a9ce9293e166ce1f972123d18c07b510a349e/Dockerfile#L4)):</sup>
Cool, thanks for explaining.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/116)

**Pull request merged**
