### PR TITLE
[FLOC-2749] Upgrade pip on buildslaves.

### PR DESCRIPTION
**Pull request by tomprince**
https://clusterhq.atlassian.net/browse/FLOC-2749

This upgrades the pip used by all the builders to match the one required by buildbot. It does this by upgrading virtualenv to a version that bundles the appropriate pip.

You can see that the appropriate pip is installed [here](http://build.staging.clusterhq.com/builders/flocker-docs/builds/5/steps/install-dependencies/logs/stdio) (for the ubuntu slave) or [here](http://build.staging.clusterhq.com/builders/flocker-centos-7/builds/4/steps/install-dependencies/logs/stdio) (for the centos slave).

I haven't applied the changes to OSX or soyoustart machine yet. (I'll do that once this branch is accepted).

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/138)

### CODE REVIEW

**Comment by jml** [comment]
I thought I reviewed tasks from @adamtheturtle yesterday that did the upgrades to OS X and soyoustart. Maybe worth at least pinging him.

In any case, the change looks good. OK to merge.

:+1:

---

Reviewed 5 of 5 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/138)

**Comment by tomprince** [comment]
My understanding is that Adam upgraded pip but not virtualenv, so that the pip in the virtualenvs created wasn't upgraded.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/138)

**Comment by adamtheturtle** [comment]
If I understand correctly, the AMI changes were never deployed.

**Comment by adamtheturtle** [comment]
Jon and I will work on that now as it is causing us problems.

**Pull request merged**
