### PR TITLE
  [FLOC-1625] Use Flocker version in Homebrew recipes for releases

### PR DESCRIPTION
**Pull request by jongiddy**
The Homebrew recipe uses the Git commit SHA to make the class names work without mangling.

Since marketing, pre- and dev releases use simpler version numbering, we can use those directly. This allows the Buildbot-generated recipe to be used for the release.

### CODE REVIEW

**Comment by jongiddy** [comment]
Looking over this with @wallrj realise that recipe created on Buildbot contains link to Flocker distribution on Buildbot, where the released recipe must contain a link to Google Storage.

**Comment by tomprince** [comment]
Closing this, as the previous comment make it appear that buildbot doesn't generate a usable recipe.

**Comment by jongiddy** [comment]
Re-opening, as we are working to resolve the problem

**Comment by jongiddy** [comment]
Closing again, as we now plan to perform Homebrew steps for release separately to CI.

**Pull request closed without merging**
