### PR TITLE
S3 tutorial floc 1718

### PR DESCRIPTION
**Pull request by adamtheturtle**
This should be merged at the same time as https://github.com/ClusterHQ/flocker/pull/1353

### CODE REVIEW

**Comment by tomprince** [comment]
The code here looks good. I am testing.

**Comment by tomprince** [comment]
It appears that ClusterHQ/flocker#1349 broke gsutil (since it depends on a version of boto incompatible with it). We might as well get rid of the usage of gsutil here. (Elsewhere we use `s3cmd`).

**Comment by adamtheturtle** [comment]
I have made a couple of changes, so please review the three minor commits. However I have not tested them because I am having trouble pushing to the staging server and think that perhaps it would be easier to wait for you ( @tomprince ) to come online and help me do that than to set up a new one.

**Comment by wallrj** [comment]
@adamtheturtle You mentioned last week that some of these instructions will be useful in setting up a PistonCloud build slave. I'll let you know how I get on.

**Comment by adamtheturtle** [comment]
@wallrj Thanks, that and also that it'd be nice to have similar instructions for PistonCloud. Perhaps this README is getting to the point where it has outgrown itself and we should be thinking about docs structure.

**Comment by tomprince** [comment]
`s3cmd` isn't installed on the vagrant slave.

**Comment by tomprince** [comment]
Once that is addressed, and assuming that that it works in staging, this is good to merge.

**Comment by adamtheturtle** [comment]
This will also cover FLOC-1402.

**Pull request merged**
