### PR TITLE
[FLOC-1948] Collect run-acceptance-tests logs.

### PR DESCRIPTION
**Pull request by tomprince**
https://clusterhq.atlassian.net/browse/FLOC-1948

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/90)

### CODE REVIEW

**Comment by itamarst** [comment]
I will assume you know what you're doing :grinning:

**Comment by itamarst** [comment]
Merge when applicable.

**Comment by itamarst** [comment]
So actually, just so I understand this: will this only apply to vagrant test runs?

**Comment by tomprince** [comment]
Nope. For silly historical reasons, all the acceptance tests builders are defined in `..flocker_vagrant`. (Mostly because the original acceptance tests were defined there).

**Pull request merged**
