### PR TITLE
[FLOC-2818] Remove vagrant box files

### PR DESCRIPTION
**Pull request by adamtheturtle**
This is a modification to the README to change from removing all Vagrant boxes to removing only those > 14 days old. Also boxes in use won't be removed. The next step (getting Buildbot to run this periodically, and removing it from the README) is at https://clusterhq.atlassian.net/browse/FLOC-2816.

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/build.clusterhq.com/128)

### CODE REVIEW

**Comment by jml** [comment]
Out of curiosity, why did you choose to take this intermediate step? 

I'm asking because I'm uncomfortable having such complicated code in the `README`, and I don't understand why the script isn't just in its own file. Could you please get back to me on this before merging? 

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/build.clusterhq.com/128)

**Comment by adamtheturtle** [comment]
I vaguely remember that setting up a testing master and an OnMetal Vagrant slave takes quite some time. That plus I don't have a good idea of how long setting up a periodic task and testing it will take meant that I thought it best to have a works-for-now solution in case the problem pops up again before the Buildbot work is done. How about I leave this open and work on the Buildbot side, and resubmit this / discuss it with you if it seems like that will take a long time?

**Comment by jml** [comment]
That sounds like a good plan.

**Comment by jml** [comment]
(Also, note that there's a thing you can do in rST where it inlines a script from a file, which is probably a nicer thing to do)

**Pull request closed without merging**
